const fs = require('fs');
const path = require('path');
const sharp = require('sharp');

const sourceDir = path.join(__dirname, 'party-pictures');
const webDir = path.join(__dirname, 'photos');
const downloadDir = path.join(__dirname, 'party-downloads');
const photosJsPath = path.join(__dirname, 'photos.js');

const preservedWebFiles = new Set([
    'cute_fruits_animals_background.png',
    'cute_invitation_background.png'
]);

const imageExtRegex = /\.(jpg|jpeg|png|heic|webp)$/i;

function ensureDir(dirPath) {
    if (!fs.existsSync(dirPath)) {
        fs.mkdirSync(dirPath, { recursive: true });
    }
}

function clearGeneratedImages(directoryPath, preserveSet = new Set()) {
    const files = fs.readdirSync(directoryPath);
    for (const file of files) {
        const filePath = path.join(directoryPath, file);
        if (fs.statSync(filePath).isFile() && imageExtRegex.test(file) && !preserveSet.has(file)) {
            fs.unlinkSync(filePath);
        }
    }
}

function toWebpName(fileName) {
    const ext = path.extname(fileName);
    return `${path.basename(fileName, ext)}.webp`;
}

function writePhotosManifest(fileNames) {
    const fileContent = `// This file is auto-generated by optimize_photos.js\nwindow.galleryPhotos = ${JSON.stringify(fileNames, null, 4)};\n`;
    fs.writeFileSync(photosJsPath, fileContent);
}

async function optimizeImages() {
    try {
        ensureDir(sourceDir);
        ensureDir(webDir);
        ensureDir(downloadDir);

        clearGeneratedImages(webDir, preservedWebFiles);
        clearGeneratedImages(downloadDir);

        const sourceFiles = fs
            .readdirSync(sourceDir)
            .filter((file) => imageExtRegex.test(file))
            .sort((a, b) => a.localeCompare(b));

        const generatedFiles = [];

        for (const file of sourceFiles) {
            const sourcePath = path.join(sourceDir, file);
            const outputName = toWebpName(file);
            const webPath = path.join(webDir, outputName);
            const downloadPath = path.join(downloadDir, outputName);

            console.log(`Processing ${file}...`);

            // Display-optimized image for the gallery.
            await sharp(sourcePath)
                .rotate()
                .resize({
                    width: 1600,
                    fit: 'inside',
                    withoutEnlargement: true
                })
                .webp({ quality: 78, effort: 6 })
                .toFile(webPath);

            // Download-optimized image balancing quality and file size.
            await sharp(sourcePath)
                .rotate()
                .resize({
                    width: 2800,
                    fit: 'inside',
                    withoutEnlargement: true
                })
                .webp({ quality: 92, effort: 6 })
                .toFile(downloadPath);

            generatedFiles.push(outputName);
        }

        writePhotosManifest(generatedFiles);
        console.log(`Optimization complete. Generated ${generatedFiles.length} photos.`);
    } catch (error) {
        console.error('Error optimizing images:', error);
        process.exitCode = 1;
    }
}

optimizeImages();
