const fs = require('fs');
const path = require('path');

const photosDir = path.join(__dirname, 'photos');
const outputFile = path.join(__dirname, 'photos.js');

try {
    const files = fs.readdirSync(photosDir).filter(file => {
        // Find all image files ignoring case
        return file.match(/\.(jpg|jpeg|png|gif|heic|webp)$/i);
    });

    const fileContent = `// This file is auto-generated by update_photos.js\nconst galleryPhotos = ${JSON.stringify(files, null, 4)};\n`;
    fs.writeFileSync(outputFile, fileContent);
    console.log(`Successfully updated photos.js with ${files.length} images.`);
} catch (err) {
    if (err.code === 'ENOENT') {
        console.error('Error: "photos" directory not found.');
    } else {
        console.error('Error reading photos directory:', err);
    }
}
